[package]
name = "macaroni"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7", features = [ "alloc" ] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
