((fn fst (list-variable)
    (car list-variable))
 (fn snd (list-variable)
    (car (cdr list-variable)))
 (fn mlet-helper (bind-list body)
    (if (empty? bind-list)
        body
        (let pair (fst bind-list)
          (list
            (quote let)
            (fst pair)
            (snd pair)
            (mlet-helper (cdr bind-list) body)))))
 (macro mlet (bind-list body)
    (mlet-helper bind-list body))
 (mlet ((a 4) (b 3) (c 5) (d 8)) (+ d (* c (+ a b)))))
