((declare map (forall a (forall b (-> ((-> (a) b) (List a)) (List b)))))
 (fn map (f input-list)
  (if (empty? input-list)
   (list)
   (cons (car input-list) (map f (cdr input-list)))))
 (map (lambda (elem) "hey") (list 1 4 7 8)))
